.PHONY: clean All

All:
	@echo "----------Building project:[ Project_01 - Debug ]----------"
	@cd "Project_01" && "$(MAKE)" -f  "Project_01.mk"
clean:
	@echo "----------Cleaning project:[ Project_01 - Debug ]----------"
	@cd "Project_01" && "$(MAKE)" -f  "Project_01.mk" clean
